# Schema for the configuration files of the ForceAnon module.

slakb_general.settings:
  type: mapping
  label: 'slakb_general settings'
  mapping:
    redirect_path:
      type: string
      label: 'Redirect path'
 